### PR TITLE
Fix path comparision to be OS independant

### PR DESCRIPTION
**Pull request by SinTh0r4s**
I love the idea of your tool, but it only works on unix system. This fix will have it work on windows as well

### CODE REVIEW

**Review by DeanWay — APPROVED** [review]
Nice. I haven’t tried it on windows but I’m happy to merge if it works for you. Would this means you would need to make your path config widows specific for a given project?

**Comment by SinTh0r4s** [comment]
Good point.  You would need to specify paths for windows and linux if you work on cross-platform. I'll check it again

**Comment by SinTh0r4s** [comment]
I switched to path normalization. This will allow arbitrary path formats for any platform. I tested it on windows, but I have no UNIX on hand.

@DeanWay: The PR is ready to merge. I don't have the rights to do so

**Comment by SinTh0r4s** [comment]
push

**Comment by DeanWay** [comment]
this is released in 0.5.0

**Pull request merged**
